Fix Bug: src/page-objects/ConfluenceUser.ts(96,23): error TS2345: Argument of type 'Locator' is not assignable to parameter of type 'By'.
Type 'ProtractorLocator' is not assignable to type 'By'.
Property 'toString' is optional in type 'ProtractorLocator' but required in type 'By'.